server:
  port: 8082
  servlet:
    context-path: /ui
  session:
    cookie:
      name: UISESSION
spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: SampleClientId
            client-secret: secret
            client-name: Client for user scope
            provider: my-oauth-provider
            scope: user_info
            redirect-uri: http://localhost:8082/ui/login/oauth2/code/my-oauth-provider
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          my-oauth-provider:
            authorization-uri: http://localhost:8081/oauth/authorize
            token-uri: http://localhost:8081/oauth/token
            user-info-uri: http://localhost:8081/user/me
            user-info-authentication-method: header
            jwk-set-uri: http://my-auth-server/token_keys
            user-name-attribute: name
logging.level:
  org.springframework:
      security.web: DEBUG
