server:
  port: 8083
spring:
  application:
    name: zipkin-server1
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8082/eureka/
logging:
  level:
    root: INFO